version: '3.4'

services:
  db:
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=12345
    healthcheck:
      #test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    build:
      context: ./db
      dockerfile: ./Dockerfile
    ports:
      - 5432:5432

  parser:
    build:
      context: ./parser
      dockerfile: ./Dockerfile
    command: python parser.py
    depends_on:
      db:
        condition: service_healthy

  my_tgbot:
    build:
      context: ./my_tgbot
      dockerfile: ./Dockerfile
    command: python bot.py
    depends_on:
      db:
       condition: service_healthy
